# Generated by Django 4.2.30 on 2026-04-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
